-- 001_initial_schema.sql — KAN-39
--
-- The landing table for the approved 0.1.0 TelemetryPayload and its nested StateEvent,
-- plus the two non-owner roles that read and append to it.
--
-- Scope, per the Lead decision recorded on KAN-39 (14 September 2026): this migration
-- establishes the existing 0.1.0 schema only. run_id belongs here because it is a
-- TelemetryPayload 0.1.0 field. A boots table, boot_id and the producer/boot ordering
-- columns are deliberately absent; they arrive as an additive 002 migration under
-- KAN-40. run_id and boot_id are not the same category of identifier.
--
-- The runner wraps this file in one transaction and records it in schema_migrations.
-- Do not add BEGIN/COMMIT here, and do not edit this file once it has been applied:
-- its checksum is recorded and a changed file stops startup.
--
-- Column mapping to core/schema.py, which is the authority:
--   TelemetryPayload.schema_version -> schema_version
--   TelemetryPayload.run_id         -> run_id
--   TelemetryPayload.event_id       -> event_id
--   StateEvent.device_id            -> device_id
--   StateEvent.previous_state       -> previous_state
--   StateEvent.new_state            -> new_state
--   StateEvent.reason               -> reason
--   StateEvent.timestamp            -> event_timestamp
--   StateEvent.expires_at           -> expires_at
-- Only `timestamp` is renamed, because it is a type name in SQL and would need
-- quoting at every use. The rename is presentation; the contract is unchanged.

CREATE TABLE events (
    event_id        text             PRIMARY KEY,
    run_id          text             NOT NULL,
    schema_version  text             NOT NULL,
    device_id       text             NOT NULL,
    previous_state  text             NOT NULL,
    new_state       text             NOT NULL,
    reason          text             NOT NULL,
    -- UTC Unix seconds, stored as sent. Kept as the wire value rather than converted,
    -- so what the producer claimed is always recoverable byte-for-byte.
    event_timestamp double precision NOT NULL,
    expires_at      double precision,
    -- Derived, never written by the consumer: Grafana and time-range queries need a
    -- real instant, and a generated column cannot drift from the value above.
    event_time      timestamptz      GENERATED ALWAYS AS (to_timestamp(event_timestamp)) STORED,
    -- Consumer-side arrival, not part of any contract. Event time and ingest time must
    -- stay separable: G10 latency is the difference, and collapsing them would hide it.
    ingested_at     timestamptz      NOT NULL DEFAULT now(),

    CONSTRAINT events_schema_version_supported
        CHECK (schema_version = '0.1.0'),
    CONSTRAINT events_identifiers_are_nonempty
        CHECK (btrim(event_id) <> '' AND btrim(run_id) <> '' AND btrim(device_id) <> ''),
    CONSTRAINT events_reason_is_nonempty
        CHECK (btrim(reason) <> ''),
    CONSTRAINT events_states_are_known
        CHECK (previous_state IN ('NORMAL', 'SUSPICIOUS', 'QUARANTINED')
           AND new_state      IN ('NORMAL', 'SUSPICIOUS', 'QUARANTINED')),
    -- Mirrors StateEvent.__post_init__: a record that does not describe a transition
    -- is not a StateEvent, and expiry that precedes the event is not an expiry.
    CONSTRAINT events_describe_a_transition
        CHECK (previous_state <> new_state),
    CONSTRAINT events_expiry_follows_timestamp
        CHECK (expires_at IS NULL OR expires_at > event_timestamp),
    -- Mirrors core.schema.number(): finite and not negative. PostgreSQL treats
    -- NaN = NaN as true and sorts NaN above every number, so a self-comparison would
    -- not catch it; the value is excluded by name instead.
    -- Measured on PostgreSQL 17.6: a NaN event_timestamp is in practice rejected
    -- earlier, by to_timestamp() in the generated column ("timestamp cannot be NaN"),
    -- so that clause is defence in depth rather than the active check. A NaN
    -- expires_at has no generated column above it and is caught here.
    CONSTRAINT events_timestamps_are_finite_and_not_negative
        CHECK (event_timestamp >= 0
           AND event_timestamp <> 'NaN'::double precision
           AND event_timestamp <> 'Infinity'::double precision
           AND (expires_at IS NULL
                OR (expires_at >= 0
                    AND expires_at <> 'NaN'::double precision
                    AND expires_at <> 'Infinity'::double precision)))
);

COMMENT ON TABLE events IS
    'One row per delivered TelemetryPayload 0.1.0. event_id is the producer''s '
    'deterministic identity, so redelivery is an ON CONFLICT DO NOTHING, not a duplicate '
    'row. A QUARANTINED row is a policy decision, never evidence that traffic stopped.';

-- Per-device history, which is how both Grafana and the measurement cards read it.
CREATE INDEX events_device_time ON events (device_id, event_timestamp DESC);
-- Grafana panels filter on an instant, not on the raw double.
CREATE INDEX events_event_time ON events (event_time DESC);
-- Experiment runs are selected whole; KAN-42/43 report per run.
CREATE INDEX events_run ON events (run_id);

-- Roles. Migration authority is the table owner and is not the identity the consumer
-- runs under: a consumer compromised at runtime must not be able to alter the schema
-- or rewrite history. Neither role is given a password here, so neither can
-- authenticate until one is provisioned outside version control. Note that the
-- postgres image trusts local socket connections, so this separates authority over
-- the schema, not access from inside the container.
DO $omniguard_roles$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'omniguard_consumer') THEN
        CREATE ROLE omniguard_consumer LOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'omniguard_readonly') THEN
        CREATE ROLE omniguard_readonly LOGIN;
    END IF;
END
$omniguard_roles$;

GRANT USAGE ON SCHEMA public TO omniguard_consumer, omniguard_readonly;
REVOKE CREATE ON SCHEMA public FROM omniguard_consumer, omniguard_readonly;

-- The consumer appends and reads back for deduplication. It cannot UPDATE or DELETE:
-- telemetry history is append-only, and a consumer that can rewrite it cannot be used
-- as evidence of what was observed.
GRANT SELECT, INSERT ON events TO omniguard_consumer;

-- Dashboards read. KAN-41 uses this role, not the owner.
GRANT SELECT ON events TO omniguard_readonly;

-- schema_migrations is the runner's record. Nobody else needs to see or touch it.
REVOKE ALL ON schema_migrations FROM omniguard_consumer, omniguard_readonly;
