-- 002_boot_ordering.sql — KAN-40
--
-- Additive. 001 is applied and immutable: nothing here alters, drops or restates it.
--
-- Why this exists: ADR-0003's v2 envelope carries ordering metadata that the 0.1.0
-- payload does not, and telemetry/envelope.py decides per boot whether a producer's
-- UTC start time actually orders it against the boots already seen. That verdict lived
-- only in a consumer's memory, so a restart erased it and a clock rollback could be
-- re-read as ORDERED with no trace. This migration gives the verdict somewhere to
-- survive, which is R1's acceptance condition on this card.
--
-- Scope decision, recorded so it is not re-derived later. The KAN-40 notes of
-- 14 September 2026 ask for "boot_id on the event row". Gabriel raised with the Lead on
-- 16 September 2026 that boot_id alone cannot carry the requirement: it is not unique
-- across producers, so it cannot be joined to a boot record, and without sequence the
-- rows cannot be ordered in SQL at all — the ordering key is
-- (boot_started_at, boot_id, sequence). Şükrü approved the three-column shape
-- (producer_id, boot_id, sequence) the same day. It is written down here because an
-- applied migration cannot be corrected in place: a column missed now needs a 003.
--
-- The runner wraps this file in one transaction and records it in schema_migrations.
-- Do not add BEGIN/COMMIT here, and do not edit this file once it has been applied.

-- One row per boot a producer has presented, written the first time it is seen.
-- Append-only, like events: the verdict is a statement about what was known at first
-- sight, and a consumer that could revise it afterwards could not be used as evidence
-- that a rollback was ever observed.
CREATE TABLE boots (
    producer_id     text             NOT NULL,
    boot_id         text             NOT NULL,
    -- UTC Unix seconds as the producer reported them, stored as sent.
    boot_started_at double precision NOT NULL,
    -- telemetry.envelope.BootOrder, as decided when this boot was first seen.
    -- BootOrder.KNOWN is deliberately not storable: it is the answer to a repeat
    -- sighting, not a property of the boot, and allowing it here would let a second
    -- sighting overwrite the verdict the first one established.
    verdict         text             NOT NULL,
    first_seen_at   timestamptz      NOT NULL DEFAULT now(),

    PRIMARY KEY (producer_id, boot_id),

    CONSTRAINT boots_identifiers_are_nonempty
        CHECK (btrim(producer_id) <> '' AND btrim(boot_id) <> ''),
    CONSTRAINT boots_verdict_is_known
        CHECK (verdict IN ('ORDERED', 'UNORDERED')),
    -- Mirrors core.schema.number(), as 001 does for event_timestamp.
    CONSTRAINT boots_started_at_is_finite_and_not_negative
        CHECK (boot_started_at >= 0
           AND boot_started_at <> 'NaN'::double precision
           AND boot_started_at <> 'Infinity'::double precision)
);

COMMENT ON TABLE boots IS
    'One row per observed producer boot, written at first sight and never revised. '
    'verdict records whether the reported UTC start time ordered this boot against the '
    'boots already seen; UNORDERED means it did not, and no later sighting turns that '
    'into ORDERED.';

-- Ordering identity on the event row. Nullable on purpose: the v1 topic carries no
-- envelope, so an event delivered there has no boot identity, and inventing one would
-- be a claim the wire never made. A NULL here reads as "this event cannot be ordered
-- across boots", which is the truth about it.
ALTER TABLE events
    ADD COLUMN producer_id text,
    ADD COLUMN boot_id     text,
    ADD COLUMN sequence    integer;

ALTER TABLE events
    -- All three or none. A boot_id without its producer cannot be joined, and either
    -- without sequence cannot be ordered, so a partial identity is not a weaker
    -- record — it is an unusable one that would still look populated.
    ADD CONSTRAINT events_boot_identity_is_whole
        CHECK (num_nonnulls(producer_id, boot_id, sequence) IN (0, 3)),
    ADD CONSTRAINT events_boot_identifiers_are_nonempty
        CHECK (producer_id IS NULL
            OR (btrim(producer_id) <> '' AND btrim(boot_id) <> '')),
    -- telemetry.identity restarts sequence at 1 on every boot.
    ADD CONSTRAINT events_sequence_is_positive
        CHECK (sequence IS NULL OR sequence >= 1),
    -- An event that names a boot nobody recorded cannot be ordered against anything,
    -- and its verdict would be unknowable. The consumer writes the boot row and the
    -- event row in one transaction, so this is satisfiable without a deferred check.
    ADD CONSTRAINT events_boot_is_recorded
        FOREIGN KEY (producer_id, boot_id) REFERENCES boots (producer_id, boot_id);

COMMENT ON COLUMN events.boot_id IS
    'The boot that produced this event, NULL for v1-topic deliveries that carry no '
    'envelope. Joined with producer_id to boots; with sequence it completes the '
    'ADR-0003 ordering key (boot_started_at, boot_id, sequence).';

-- Onur's acceptance condition: which boots a run passed through must be answerable
-- from the event row itself, not reconstructed from timestamps.
CREATE INDEX events_run_boot ON events (run_id, producer_id, boot_id);
-- Replay of one boot in producer order, which is what an ordering-dependent
-- measurement reads.
CREATE INDEX events_boot_sequence ON events (producer_id, boot_id, sequence);

-- Ordering-dependent measurements must exclude runs that touched an unordered boot,
-- and must report how many they excluded rather than quietly merging them. Naming the
-- set here means every reader — KAN-42/43 and the KAN-41 dashboard — excludes the same
-- rows by the same rule instead of each writing its own.
CREATE VIEW unordered_runs AS
    SELECT DISTINCT events.run_id
    FROM events
    JOIN boots USING (producer_id, boot_id)
    WHERE boots.verdict = 'UNORDERED';

COMMENT ON VIEW unordered_runs IS
    'Runs containing at least one event from a boot whose start time did not order it. '
    'Exclude these from ordering-dependent measurements and report the count; a run '
    'absent from this view is not thereby proven ordered, only not contradicted.';

-- 001 comments that this difference is "G10 latency". It is not: the two clocks are
-- unaligned, and now() is transaction-start time rather than evidence of commit. The
-- applied file cannot be edited, so the correction is made here, as platform/README.md
-- said it would be.
COMMENT ON COLUMN events.ingested_at IS
    'Consumer-side arrival, not part of any contract. Its difference from event_time is '
    'a wall-clock offset between two unaligned clocks, not measured G10 latency: now() '
    'is transaction-start time, not commit evidence. Keeping the columns separable is '
    'what makes a latency measurement possible; the measurement needs the clock '
    'alignment and stated uncertainty KAN-42 provides, and is reported from there.';

-- The consumer appends boots as it appends events, and reads them back to rebuild its
-- ledger at startup. It still cannot UPDATE or DELETE either table.
GRANT SELECT, INSERT ON boots TO omniguard_consumer;
GRANT SELECT ON boots TO omniguard_readonly;
GRANT SELECT ON unordered_runs TO omniguard_consumer, omniguard_readonly;
